import Head from "next/head";
import { Inter } from "next/font/google";
import PostList from "@/components/PostList";

const inter = Inter({ subsets: ["latin"] });

export const getStaticProps = async () => {
  const posts = await fetch(
    "https://jsonplaceholder.typicode.com/posts?_limit=20"
  )
    .then((res) => res.json())
    .catch((err) => console.log(err));

  return {
    props: {
      posts: posts,
    },
  };
};

export default function Home({ posts }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostList posts={posts} />
    </>
  );
}
